routes/admin.php
<?php


use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\CentroController;
use App\Http\Controllers\Admin\FacultadController;
use App\Http\Controllers\Admin\CarreraController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\EstudianteController;
use App\Http\Controllers\Admin\ActividadController;
use App\Http\Controllers\Admin\AcumuladoController;
use App\Http\Controllers\Admin\CodeController;
use App\Http\Controllers\Admin\ConstanciaController;
use App\Http\Controllers\Admin\DocumentoController;
use App\Http\Controllers\Estudiante\ConsultaController;

Route::get('', [HomeController::class, 'index'])->name("admin.home")
    ->middleware('can:admin.home');

// middlewares completos
Route::resource('centros', CentroController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->names("admin.centros");

// middlewares completos
Route::resource('facultads', FacultadController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->names("admin.facultads");

// middlewares completos
Route::resource('carreras', CarreraController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->names("admin.carreras");

// middlewares completos
Route::resource('users', UserController::class)
    ->only(['index', 'edit', 'update'])
    ->names("admin.users");

// middlewares completos
Route::resource('roles', RoleController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->names('admin.roles');

//  Middlewares completos
Route::resource('estudiantes', EstudianteController::class)
    ->only(['index', 'edit', 'update'])
    ->names('admin.estudiantes');

// Middlewares completos
Route::resource('actividads', ActividadController::class)
    ->only(['index', 'create', 'store', 'edit', 'update'])
    ->names('admin.actividads');


// Middlewares completos
Route::resource('codes', CodeController::class)
    ->only(['index', 'store','show','edit','destroy'])
    ->names('admin.codes');


// Middlewares completos
Route::resource('constancias', ConstanciaController::class)
    ->only(['index', 'show', 'edit'])
    ->names('admin.constancias');

Route::resource('validar', AcumuladoController::class)
    ->only(['index', 'show', 'edit','update','destroy'])
    ->names('admin.validars');

routes/web.php
<?php

use App\Http\Controllers\Admin\DocumentoController;
use App\Http\Controllers\Estudiante\ConsultaController;
use App\Models\Estudiante;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Input;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('consulta', [ConsultaController::class, 'index'])->name('consulta');
Route::post('registro', [ConsultaController::class, 'store'])->name('registro');
Route::post('acumular', [ConsultaController::class, 'update'])->name('acumular');

//Route::get('documento', [DocumentoController::class, 'index'])->name('documento');

/*
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
*/

app/Http/Livewire/Admin/ActividadIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Actividad;
use Livewire\Component;
use Livewire\WithPagination;

class ActividadIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    }


    public function render()
    {
        $actividads = Actividad::where('carrera_id',auth()->user()->carrera_id)
                                ->where('nombre','LIKE','%'.$this->search.'%')
                                //->orwhere('cuenta','LIKE','%'.$this->search.'%') 
                                ->latest('id')
                                ->paginate();
        return view('livewire.admin.actividad-index',compact('actividads'));
        
    }
}

app/Http/Livewire/Admin/CodeIndex.php
<?php

namespace App\Http\Livewire\Admin;

use Livewire\Component;
use Livewire\WithPagination;
use App\Models\Actividad;

class CodeIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    }


    public function render()
    {
        $actividads = Actividad::where('carrera_id',auth()->user()->carrera_id)
                                ->where('nombre','LIKE','%'.$this->search.'%')
                                //->orwhere('cuenta','LIKE','%'.$this->search.'%') 
                                ->latest('id')
                                ->paginate();
        return view('livewire.admin.code-index',compact('actividads'));
    }
}

app/Http/Livewire/Admin/ConstanciaIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Estudiante;
use Livewire\Component;
use Livewire\WithPagination;


class ConstanciaIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    }
    public function render()
    {
        $carrera= auth()->user();
        //return $carrera_id;
        $estudiantes = Estudiante::where('carrera_id',auth()->user()->carrera_id)
                                ->where('cuenta','LIKE','%'.$this->search.'%')
                                //->orwhere('cuenta','LIKE','%'.$this->search.'%') 
                                ->latest('id')
                                ->paginate();
        return view('livewire.admin.constancia-index',compact('estudiantes','carrera'));
    }
}

app/Http/Livewire/Admin/EstudianteIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\Estudiante;
use Livewire\Component;
use Livewire\WithPagination;

class EstudianteIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search;

    public function updatingSearch(){
        $this->resetPage();
    }
    public function render()
    {
        $carrera= auth()->user();
        //return $carrera_id;
        $estudiantes = Estudiante::where('carrera_id',auth()->user()->carrera_id)
                                ->where('cuenta','LIKE','%'.$this->search.'%')
                                //->orwhere('cuenta','LIKE','%'.$this->search.'%') 
                                ->latest('id')
                                ->paginate();
        return view('livewire.admin.estudiante-index',compact('estudiantes','carrera'));
    }
}

app/Http/Livewire/Admin/UserIndex.php
<?php

namespace App\Http\Livewire\Admin;

use App\Models\User;
use Livewire\Component;
use Livewire\WithPagination;
class UserIndex extends Component
{
    use WithPagination;
    protected $paginationTheme="bootstrap";
    public $search="";

    public function updatingSearch(){
        $this->resetPage();
    }
    public function render()
    {
        $users = User::where('name','LIKE','%'.$this->search.'%')
                       ->orwhere('email','LIKE','%'.$this->search.'%') ->paginate();
        return view('livewire.admin.user-index',compact('users'));
    }
}

app/Http/Livewire/Navigation.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Navigation extends Component
{
    public function render()
    {
        return view('livewire.navigation');
    }
}

resources/views/livewire/admin/actividad-index.blade.php
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el nombre de la actividad">
        </div>
        @can('admin.actividads.create', Model::class)
        <div class="card-header" >
            <a class="btn btn-primary" href="{{route("admin.actividads.create")}}">Nueva Actividad </a>
        </div>
            
        @endcan
        @if ($actividads->count())
            
        
        <div class="card-body">
           
            <table class="table table-stripe">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Actividad</th>
                        <th>Horas</th>
                        <th>Fecha</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($actividads as $actividad)
                    <tr>
                        <td>{{$actividad->id}}</td>
                        <td>{{$actividad->nombre}}</td>
                        <td>{{$actividad->horas}}</td>
                        <td>{{$actividad->fecha}}</td>
                        <td width="10px" >
                            @can('admin.actividads.edit')
                            <a class="btn btn-primary" href="{{route('admin.actividads.edit',$actividad)}}">Editar</a>
                            @endcan
                            
                        </td>

                    </tr>
                        
                    @endforeach

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{$actividads->links()}}
        </div>
            
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>

resources/views/livewire/admin/code-index.blade.php
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese nombre de la actividad">
        </div>
        @if ($actividads->count())
            
        
        <div class="card-body">
           
            <table class="table table-stripe">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Actividad</th>
                        <th>Horas</th>
                        <th>Fecha</th>
                        <th style="width: 40%" colspan="3">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($actividads as $actividad)
                    <tr>
                        <td>{{$actividad->id}}</td>
                        <td>{{$actividad->nombre}}</td>
                        <td>{{$actividad->horas}}</td>
                        <td>{{$actividad->fecha}}</td>
                        <td  >
                            @can('admin.codes.create')
                            <a class="btn btn-primary" href="{{route('admin.codes.edit',$actividad->id)}}">Generar Códigos</a>
                            @endcan
                            
                        </td>
                        <td  >
                            @can('admin.codes.create')
                            <a class="btn btn-success" href="{{route('admin.codes.show',$actividad->id)}}">Ver Códigos</a>
                            @endcan
                            
                        </td>
                        <td  >
                            @can('admin.codes.create')
                            <a class="btn btn-info" href="{{route('admin.validars.edit',$actividad->id)}}">Validar</a>
                            @endcan
                            
                        </td>

                    </tr>
                        
                    @endforeach

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{$actividads->links()}}
        </div>
            
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>

resources/views/livewire/admin/constancia-index.blade.php
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el número de cuenta del estudiante">
        </div>
        @if ($estudiantes->count())
            
        
        <div class="card-body">
           
            <table class="table table-stripe">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>nombre</th>
                        <th>Cuenta</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($estudiantes as $estudiante)
                    <tr>
                        <td>{{$estudiante->id}}</td>
                        <td>{{$estudiante->nombre.' '.$estudiante->apellido}}</td>
                        <td>{{$estudiante->cuenta}}</td>
                        <td>{{$estudiante->correo}}</td>
                        <td>{{$estudiante->telefono}}</td>
                        <td width="30px" >
                            @can('admin.constancias.edit')
                            <a class="btn btn-primary" href="{{route('admin.constancias.edit',$estudiante)}}">Generar Constancia</a>
                            @endcan
                            
                        </td>

                    </tr>
                        
                    @endforeach

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{$estudiantes->links()}}
        </div>
            
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>

resources/views/livewire/admin/estudiante-index.blade.php
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese el número de cuenta del estudiante">
        </div>
        @if ($estudiantes->count())
            
        
        <div class="card-body">
           
            <table class="table table-stripe">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>nombre</th>
                        <th>Cuenta</th>
                        <th>Correo</th>
                        <th>Telefono</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($estudiantes as $estudiante)
                    <tr>
                        <td>{{$estudiante->id}}</td>
                        <td>{{$estudiante->nombre.' '.$estudiante->apellido}}</td>
                        <td>{{$estudiante->cuenta}}</td>
                        <td>{{$estudiante->correo}}</td>
                        <td>{{$estudiante->telefono}}</td>
                        <td width="10px" >
                            @can('admin.estudiantes.edit')
                            <a class="btn btn-primary" href="{{route('admin.estudiantes.edit',$estudiante)}}">Editar</a>
                            @endcan
                            
                        </td>

                    </tr>
                        
                    @endforeach

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{$estudiantes->links()}}
        </div>
            
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>

resources/views/livewire/admin/user-index.blade.php
<div>
    <div class="card">
        <div class="card-header">
            <input wire:model="search" class="form-control" placeholder="Ingrese nombre o correo de usuario" type="text">
        </div>
        @if ($users->count())
            
        
        <div class="card-body">
            <table class="table table-stripe">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>nombre</th>
                        <th>Email</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                    <tr>
                        <td>{{$user->id}}</td>
                        <td>{{$user->name}}</td>
                        <td>{{$user->email}}</td>
                        <td width="10px" >
                            @can('admin.users.edit')
                            <a class="btn btn-primary" href="{{route('admin.users.edit',$user)}}">Editar</a>
                            @endcan
                            
                        </td>

                    </tr>
                        
                    @endforeach

                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {{$users->links()}}
        </div>
            
        @else
        <div class="card-body">
            <strong>No hay registros</strong>
        </div>
        @endif
    </div>
</div>